### ISSUE TITLE
Please update the engines and test it

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/google-pubsub#1]
@zubairov engines need to be updated before this can be pushed into elastic.io environment.

I could push it with:
```
"engines": {
    "node": "^8.4.0",
    "npm": ">=5.4"
  },
```

**Comment by kirill-levitskiy** [comment]
Done https://github.com/elasticio/google-pubsub/commit/a143372c3d910fff28a071a51f0a258ad586992c
