### ISSUE TITLE
Increase Google Pub/Sub maximum number of messages limit

### ISSUE THREAD

**Issue by MykytaDuniashev** [elasticio/google-pubsub#25]
#  Feature Request

## Description

The Google Pub/Sub subscribe trigger has a hard limitation of 100 msg per minute:
https://github.com/elasticio/google-pubsub/blob/0939daeb3fffcfcb9a834b2d7ef4e7991fc6125f/lib/triggers/pull.js#L49
One of our clients wants to consume a high load of messages (approx. 10-30k messages per day). Unfortunately, the trigger only consumes 100 messages per minute which is not what they expect.

[Link ](https://elasticio.slack.com/archives/C069QAMQ38F/p1705930476053829) to the Slack conversation.

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/google-pubsub/releases/tag/1.8.0
